CREATE OR REPLACE PROCEDURE borrar_centro(
  v_fuente IN CENTROS.ID%TYPE, v_destino IN CENTROS.ID%TYPE
)AS
    E_FALLO_FUENTE EXCEPTION;
    E_FALLO_DESTINO EXCEPTION;
    E_FALLO_TRANSFERIR EXCEPTION;
    V_TEMP CENTROS.ID%TYPE;
  BEGIN
    SELECT ID INTO V_TEMP FROM CENTROS WHERE ID = v_fuente;
    IF SQL%NOTFOUND THEN
      RAISE E_FALLO_FUENTE;
    ELSE
      SELECT ID into V_TEMP FROM CENTROS WHERE ID = v_destino;
      IF SQL%NOTFOUND THEN
        RAISE E_FALLO_DESTINO;
      ELSE
        UPDATE TRABAJADOR SET ID=v_destino WHERE ID=v_fuente;
        IF SQL%NOTFOUND THEN
          RAISE E_FALLO_TRANSFERIR; 
        END IF;
      END IF;
    END IF;
  EXCEPTION
    WHEN E_FALLO_FUENTE THEN
      RAISE_APPLICATION_ERROR(-20111,'No se ha encontrado el centro a borrar.');
    WHEN E_FALLO_DESTINO THEN
      RAISE_APPLICATION_ERROR(-20111,'No se ha encontrado el centro de destino.');
    when E_FALLO_TRANSFERIR THEN
      RAISE_APPLICATION_ERROR(-20112,'Error al transferir los trabajadores.');
  END;
          

CREATE OR REPLACE PROCEDURE buscar_centro_por_nombre(
  v_nCentro IN CENTROS.NOMBRE%TYPE, v_idCentro OUT CENTROS.IDCENTRO%TYPE
)AS
    E_CENTRO_ERRONEO EXCEPTION;
  BEGIN
    SELECT IDCENTRO INTO v_idCentro FROM CENTRO WHERE UPPER(NOMBRE) LIKE UPPER(V_NCENTRO);
    IF SQL%NOTFOUND THEN
      RAISE E_CENTRO_ERRONEO;
    END IF;
  EXCEPTION
    WHEN E_CENTRO_ERRONEO THEN
      RAISE_APPLICATION_ERROR(-20111,'No se ha encontrado el centro.');
  END;
  
CREATE OR REPLACE FUNCTION buscar_centro_por_nombre
    (v_nCentro IN CENTROS.NOMBRE%TYPE)
    return NUMBER
  IS
  v_idCentro CENTROS.IDCENTRO%TYPE;
  E_CENTRO_ERRONEO EXCEPTION;
  BEGIN
    SELECT IDCENTRO INTO v_idCentro FROM CENTRO WHERE UPPER(NOMBRE) LIKE UPPER(V_NCENTRO);
    IF SQL%NOTFOUND THEN
      RAISE E_CENTRO_ERRONEO;
    END IF;
  RETURN v_idCentro;
  EXCEPTION
    WHEN E_CENTRO_ERRONEO THEN
      RAISE_APPLICATION_ERROR(-20111,'No se ha encontrado el centro.');
  END buscar_centro_por_nombre;
  