CREATE OR REPLACE PROCEDURE borrar_centro(
  v_fuente IN CENTROS.idCentro%TYPE, v_destino IN CENTROS.idCentro%TYPE
)AS
  DECLARE
    E_FALLO_FUENTE EXCEPTION;
    E_FALLO_DESTINO EXCEPTION;
  BEGIN
    SELECT IDCENTRO FROM CENTROS WHERE IDCENTRO = v_fuente;
    IF SQL%NOTFOUND THEN
      RAISE E_FALLO_FUENTE;
    ELSE
      SELECT IDCENTRO FROM CENTROS WHERE IDCENTRO = v_destino;
      IF SQL%NOTFOUND THEN
        RAISE E_FALLO_DESTINO;
      ELSE
        UPDATE TRABAJADOR SET IDCENTRO=v_destino WHERE IDCENTRO=v_fuente;
        IF SQL%NOTFOUND THEN
          RAISE E_FALLO_TRANSFERIR
          
      END IF;
    END IF;
  EXCEPTION
    WHEN E_FALLO_FUENTE THEN
      RAISE_APPLICATION_ERROR(-20111,'No se ha encontrado el centro a borrar.');
    WHEN E_FALLO_DESTINO THEN
      RAISE_APPLICATION_ERROR(-20111,'No se ha encontrado el centro de destino.');
  END;
          

CREATE OR REPLACE PROCEDURE buscar_centro_por_nombre(
  v_nCentro IN CENTROS.NOMBRE%TYPE, v_idCentro OUT CENTROS.IDCENTRO%TYPE
)AS
    E_CENTRO_ERRONEO EXCEPTION;
  BEGIN
    SELECT IDCENTRO INTO v_idCentro FROM CENTRO WHERE UPPER(NOMBRE) LIKE UPPER(V_NCENTRO);
    IF SQL%NOTFOUND THEN
      RAISE E_CENTRO_ERRONEO;
    END IF;
  EXCEPTION
    WHEN E_CENTRO_ERRONEO THEN
      RAISE_APPLICATION_ERROR(-20111,'No se ha encontrado el centro.');
  END;
  
  CREATE PROCEDURE buscar_centro_por_nombre(
  v_nCentro IN CENTROS.NOMBRE%TYPE, v_nCentros IN CENTROS.NOMBRE%TYPE, v_idCentro OUT CENTROS.IDCENTRO%TYPE
)AS
    E_CENTRO_ERRONEO EXCEPTION;
  BEGIN
    SELECT IDCENTRO INTO v_idCentro FROM CENTRO WHERE UPPER(NOMBRE) LIKE UPPER(V_NCENTRO);
    IF SQL%NOTFOUND THEN
      RAISE E_CENTRO_ERRONEO;
    END IF;
  EXCEPTION
    WHEN E_CENTRO_ERRONEO THEN
      RAISE_APPLICATION_ERROR(-20111,'No se ha encontrado el centro.');
  END;